version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: timekeeping-db
    restart: always
    environment:
      POSTGRES_DB: timekeeping-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: timekeeping-redis
    restart: always
    ports:
      - "6379:6379"

  migration:
    build: .
    container_name: timekeeping-migration
    env_file: .env
    environment:
      - DATABASE_HOST=db # Trỏ vào service name 'db'
      - REDIS_HOST=redis
    command: yarn migration:run
    depends_on:
      - db

  api-app:
    build: .
    container_name: timekeeping-api
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    command: node dist/main
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migration:
        condition: service_completed_successfully

  worker:
    build: .
    container_name: timekeeping-worker
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    command: node dist/main-worker
    depends_on:
      - db
      - redis
      - migration

volumes:
  postgres_data: